# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0003_results_status_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='task_id',
            new_name='pid',
        ),
    ]
