# Generated by Django 2.0.4 on 2018-05-01 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_auto_20170701_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.IntegerField(blank=True, db_index=True, null=True)),
                ('patch_row_start', models.IntegerField(blank=True, null=True)),
                ('patch_row_end', models.IntegerField(blank=True, null=True)),
                ('patch_col_start', models.IntegerField(blank=True, null=True)),
                ('patch_col_end', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'PatchClass',
            },
        ),
        migrations.CreateModel(
            name='PNstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_class', models.CharField(blank=True, db_index=True, max_length=70, null=True)),
                ('neg_class', models.CharField(blank=True, max_length=70, null=True)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('true_pos', models.IntegerField(blank=True, null=True)),
                ('true_neg', models.IntegerField(blank=True, null=True)),
                ('false_pos', models.IntegerField(blank=True, null=True)),
                ('false_neg', models.IntegerField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, max_length=10, null=True)),
                ('exclude_class_indx', models.CharField(blank=True, max_length=50, null=True)),
                ('no_train_pos', models.IntegerField(blank=True, null=True)),
                ('no_train_neg', models.IntegerField(blank=True, null=True)),
                ('visual_result_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('train_pos_neg_ratio', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('auc', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PNstats',
            },
        ),
        migrations.CreateModel(
            name='PUstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_class', models.CharField(blank=True, db_index=True, max_length=70, null=True)),
                ('neg_class', models.CharField(blank=True, max_length=70, null=True)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('true_pos', models.IntegerField(blank=True, null=True)),
                ('true_neg', models.IntegerField(blank=True, null=True)),
                ('false_pos', models.IntegerField(blank=True, null=True)),
                ('false_neg', models.IntegerField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, max_length=10, null=True)),
                ('exclude_class_indx', models.CharField(blank=True, max_length=50, null=True)),
                ('no_train_pos_labelled', models.IntegerField(blank=True, null=True)),
                ('no_train_pos_unlabelled', models.IntegerField(blank=True, null=True)),
                ('no_train_neg_unlabelled', models.IntegerField(blank=True, null=True)),
                ('visual_result_filename', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('train_pos_neg_ratio', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('auc', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PUstats',
            },
        ),
        migrations.AlterField(
            model_name='results',
            name='percentage_done',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='results',
            name='status_text',
            field=models.CharField(default='processing', max_length=30),
        ),
    ]
