# Generated by Django 2.0.4 on 2018-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_auto_20180501_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchclass',
            name='data_name',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pnstats',
            name='data_name',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pustats',
            name='data_name',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True),
        ),
    ]
