# Generated by Django 2.0.4 on 2018-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0006_auto_20180501_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnstats',
            old_name='no_train_neg',
            new_name='no_train_neg_unlabelled',
        ),
        migrations.RenameField(
            model_name='pnstats',
            old_name='no_train_pos',
            new_name='no_train_pos_labelled',
        ),
        migrations.AddField(
            model_name='pnstats',
            name='no_train_pos_unlabelled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
