# Generated by Django 2.0.4 on 2019-01-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_auto_20180623_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnstats',
            name='baseline',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pnstats',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pustats',
            name='baseline',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pustats',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
