# Generated by Django 2.0.4 on 2019-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0009_auto_20190115_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnstats',
            name='convergence_plot_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pnstats',
            name='experiment_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pnstats',
            name='preprocessing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pustats',
            name='convergence_plot_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pustats',
            name='experiment_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pustats',
            name='preprocessing_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
