# Generated by Django 2.0.4 on 2019-03-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0010_auto_20190330_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pustats',
            old_name='train_pos_neg_ratio',
            new_name='train_neg_pos_ratio',
        ),
        migrations.AddField(
            model_name='pustats',
            name='unlabelled_prior',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
