# Generated by Django 2.0.4 on 2019-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0011_auto_20190331_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnstats',
            name='baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pnstats',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pustats',
            name='baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pustats',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
